version: '3.4'

services:

  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    restart: always
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - rede-network

  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rede-network
        
  user-profile-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: user_profile_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3312
    ports:
      - 3312:3312
    expose:
      - 3312
    networks:
      - rede-network
      
  naming-server:
    build: 
      dockerfile: naming-server/Dockerfile
    ports:
      - 8761:8761
    networks:
      - rede-network    
    
networks:
  rede-network:
    driver: bridge