server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin-server:9411/
    sender:
      type: rabbit 
  rabbitmq:
    addresses: amqp://guest:guest@localhost:5672
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-profile-service
        uri: lb://user-profile-service
        predicates:
        - Path=/user-profile-service/**
        filters:
        - AuthenticationFilter
      - id: oauth-service
        uri: lb://oauth-service        
        predicates:
        - Path=/oauth-service/**
        filters:
        - AuthenticationFilter
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  sleuth:
    sampler:
      probability: 1.00
