server:
  port: 8300
eureka:
  client:
    refresh:
      enable: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: oauth-service
  zipkin:
    base-url: http://zipkin-server:9411/
    sender:
      type: rabbit
  rabbitmq:
    addresses: amqp://guest:guest@localhost:5672
  sleuth:
    sampler:
      probability: 1.00
springdoc:
  api-docs:
    path: oauth-service/v3/api-docs
